[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stefanobaldo/seedstone"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [] }

[workspace.lints.clippy]
disallowed_methods = "deny"
disallowed_types = "deny"

[workspace.dependencies]
tokio = { version = "1", features = ["rt", "macros", "sync", "time", "io-util"] }
turmoil = "=0.7.2"
siphasher = "1"
rand = "0.9"
rand_chacha = "0.9"
